import { FigureRecord } from "./types";

const figureTitlePattern = /^\s*#\s*figure\s*:\s*(.+?)\s*$/i;
const figureTagsPattern = /^\s*#\s*tags\s*:\s*(.+?)\s*$/i;

export interface CellFigureMetadata {
    titles: readonly string[];
    tags: string[];
    codeSnippet: string;
    cellSource: string;
    notebookName: string;
}

interface FigureMetadataHeader {
    lines: string[];
    firstNonEmptyIndex: number;
    titles: readonly string[];
    tags: string[];
}

export function figureMetadata(
    source: string,
    notebookName: string
): CellFigureMetadata {
    const { lines, firstNonEmptyIndex, titles, tags } = figureMetadataHeader(source);
    const snippetLines = lines
        .slice(titles.length > 0 ? firstNonEmptyIndex + 1 : 0)
        .filter(
            (line) =>
                line.trim().length > 0 &&
                !figureTagsPattern.test(line)
        )
        .slice(0, 4);
    const codeSnippet = snippetLines.join("\n") || "No code available.";

    return {
        titles,
        tags,
        codeSnippet,
        cellSource: source,
        notebookName,
    };
}

/**
 * A deliberately small fingerprint for source edits that affect Clio's
 * presentation metadata. Code-only changes retain their cached figures until
 * an output changes, while title and tag edits can refresh immediately.
 */
export function figureMetadataSignature(source: string): string {
    const { titles, tags } = figureMetadataHeader(source);
    return JSON.stringify([titles, tags]);
}

/**
 * Replace only the presentation metadata for figures generated by one cell.
 * Image ids, bytes, and versions are intentionally preserved.
 */
export function updateCellFigureMetadata(
    figures: readonly FigureRecord[],
    cellIndex: number,
    source: string,
    notebookName: string
): FigureRecord[] {
    const metadata = figureMetadata(source, notebookName);
    let figureIndex = 0;

    return figures.map((figure) => {
        if (figure.cellIndex !== cellIndex) {
            return figure;
        }

        const { title: _previousTitle, ...record } = figure;
        const updated = {
            ...record,
            ...figureRecordMetadata(metadata, figureIndex),
        };

        figureIndex += 1;
        return updated;
    });
}

export function figureRecordMetadata(
    metadata: CellFigureMetadata,
    figureIndex: number
): Pick<
    FigureRecord,
    "title" | "tags" | "codeSnippet" | "cellSource" | "searchText"
> {
    const title = metadata.titles.length === 1
        ? metadata.titles[0]
        : metadata.titles[figureIndex];

    return {
        ...(title ? { title } : {}),
        tags: metadata.tags,
        codeSnippet: metadata.codeSnippet,
        cellSource: metadata.cellSource,
        searchText: [
            metadata.notebookName,
            title ?? "",
            metadata.tags.join(" "),
            metadata.codeSnippet,
            metadata.cellSource,
        ]
            .join("\n")
            .toLowerCase(),
    };
}

export function sourceText(source: string | string[] | undefined): string {
    return Array.isArray(source) ? source.join("") : source ?? "";
}

export function imageId(
    notebookUri: string,
    cellIndex: number,
    outputIndex: number,
    itemIndex: number
): string {
    return `${notebookUri}::${cellIndex}:${outputIndex}:${itemIndex}`;
}

function figureMetadataHeader(source: string): FigureMetadataHeader {
    const lines = source.replace(/\r\n/g, "\n").split("\n");
    const firstNonEmptyIndex = lines.findIndex((line) => line.trim().length > 0);
    const firstLine = firstNonEmptyIndex >= 0 ? lines[firstNonEmptyIndex] : "";
    const titles = firstLine.match(figureTitlePattern)?.[1]
        .split(",")
        .map((title) => title.trim())
        .filter(Boolean) ?? [];
    const tagsLine = lines.find((line) => figureTagsPattern.test(line));
    const tags = tagsLine
        ? tagsLine.match(figureTagsPattern)?.[1]
            .split(",")
            .map((tag) => tag.trim().toLowerCase())
            .filter(Boolean) ?? []
        : [];

    return { lines, firstNonEmptyIndex, titles, tags };
}
